- hosts: "{{ hostname }}"
  gather_facts: False
  vars:
    - packages: ["git"]
  tasks:
    - name: Installing {{ packages }} on {{ hostname }}
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"